### ISSUE TITLE
Buscar documentos para el estado del arte

### ISSUE THREAD

**Issue by maympersonal** [maympersonal/Proyecto-ML-Biologia#1]

**Comment by Daniman30** [comment]
### Podemos empezar a trabajar el estado del arte a partir de los grafos de connectedpapers.com de los 3 papers que nos dieron

**Airborne Fungi Identification by Case-Based Reasoning**
https://www.connectedpapers.com/main/2bd7af9e7008f2b54da4bc81f21ce54d8de17f5e/Airborne-Fungi-Identification-by-Case%20Based-Reasoning/graph

**Recognition of Airborne Fungi Spores in Digital Microscopic Images**
https://www.connectedpapers.com/main/585c2f9f31e537abb37e11454e3ec3c630c32c9f/Recognition-of-airborne-fungi-spores-in-digital-microscopic-images/graph

**Airborne Fungal Spore Review, New Advances and Automatisation**
https://www.connectedpapers.com/main/de0659eb9f2b231a8f70a6e588786c5af95d04ba/Airborne-Fungal-Spore-Review%2C-New-Advances-and-Automatisation/graph

Creo que son 120 papers (40 cada grafo), si nos dividimos entre los 7 sale a 17 por persona, que para los dias que tenemos hasta regresar a clases podemos revisar uno diario y sobran dias

**Comment by Daniman30** [comment]
Tabla para el estado del arte
https://docs.google.com/spreadsheets/d/1IY7Ak8975A-9kYulByVO0fSG4iZb1i-JH3OBtNwqfGU/edit?usp=sharing
